 export enum BasketActionTypes {
    ADD_BASKET_ITEM = 'ADD_BASKET_ITEM',
    REDUCE_BASKET_ITEM = 'REDUCE_BASKET_ITEM',
    REMOVE_BASKET_ITEM = 'REMOVE_BASKET_ITEM',
    ADD_BASKET_DISCOUNT = 'ADD_BASKET_DISCOUNT',
    REMOVE_BASKET_DISCOUNT = 'REMOVE_BASKET_DISCOUNT'
}